#!/usr/bin/env bash
#
# run_suite.sh — submit the 16-cell experiment matrix for the final report.
#
# Tasks   :  MMLU (en) | KMMLU (ko)
# Methods :  B1=plain
#            B2=original_tk_hypernet
#            M1=dynamic_bpe        + pretokens + M30(pretokens) + tp=0
#            U1=dynamic_bpe        + superbpe  + M30(superbpe)  + tp=0
#            U2=dynamic_bpe        + superbpe  + M30(superbpe)  + tp=M30/2
#            S1=entropy_split      + threshold=ENTROPY_THRESHOLD
#            SM1=dynamic_bpe_entropy_split + pretokens + M30(pretokens) + threshold=...
#            SM2=dynamic_bpe_entropy_split + superbpe  + M30(superbpe)  + threshold=...
#
# Reads M30 values from data/operating_points/m30_<task>_<lang>_<boundary>.json
# (generated by decoders/evaluation/compute_m30.py). The script prints every
# sbatch command first and only submits when invoked with --submit. Job IDs
# are appended to logs/suite_manifest.tsv so you can join slurm output back
# to (task, method).
#
# Usage:
#   # 1. Compute operating points first (one-time, CPU is fine):
#   python decoders/evaluation/compute_m30.py
#
#   # 2. Preview the full matrix (no sbatch calls):
#   bash scripts/run_suite.sh
#
#   # 3. Submit for real:
#   bash scripts/run_suite.sh --submit
#
# Optional env vars:
#   ENTROPY_THRESHOLD   default 3.0   (used by S1, SM1, SM2)
#   BATCH_SIZE          default 4
#   OPS_DIR             default $PROJECT_ROOT/data/operating_points
#   MANIFEST            default $PROJECT_ROOT/logs/suite_manifest.tsv

set -euo pipefail

# --- locate the repo root --------------------------------------------------
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$PROJECT_ROOT"

OPS_DIR="${OPS_DIR:-$PROJECT_ROOT/data/operating_points}"
MANIFEST="${MANIFEST:-$PROJECT_ROOT/logs/suite_manifest.tsv}"
ENTROPY_THRESHOLD="${ENTROPY_THRESHOLD:-3.0}"
BATCH_SIZE="${BATCH_SIZE:-4}"

mkdir -p "$(dirname "$MANIFEST")"

SUBMIT=0
if [[ "${1:-}" == "--submit" ]]; then
    SUBMIT=1
fi

# --- helper: read m30 from json ---------------------------------------------
# Usage: read_m30 mmlu en pretokens  → echoes the integer
read_m30() {
    local task=$1 lang=$2 boundary=$3
    local f="$OPS_DIR/m30_${task}_${lang}_${boundary}.json"
    if [[ ! -f "$f" ]]; then
        echo "ERROR: missing operating-point file $f" >&2
        echo "        Run: python decoders/evaluation/compute_m30.py" >&2
        exit 1
    fi
    python -c "import json; print(int(json.load(open(r'$f'))['m30']))"
}

# --- helper: submit one cell ------------------------------------------------
# Args: TAG TASK EXP_TYPE MERGES BOUNDARY TRANSITION_POINT
submit_cell() {
    local tag=$1 task=$2 exp_type=$3 merges=$4 boundary=$5 transition_point=$6

    # Pick the right slurm script & lang per task.
    local slurm_script lang
    if [[ "$task" == "mmlu" ]]; then
        slurm_script="decoders/evaluation/mmlu/run_mmlu.slurm"
        lang="en"
    elif [[ "$task" == "kmmlu" ]]; then
        slurm_script="decoders/evaluation/kmmlu/run_kmmlu.slurm"
        lang="ko"
    else
        echo "ERROR: unknown task $task" >&2
        exit 1
    fi

    # Compose the env-var prefix for this cell. PROJECT_ROOT is forwarded so the
    # slurm script doesn't fall back to $SCRATCH/... (which isn't set on Tillicum).
    local envs=(
        "PROJECT_ROOT=$PROJECT_ROOT"
        "EXP_TYPE=$exp_type"
        "MERGES=$merges"
        "BOUNDARY=$boundary"
        "TRANSITION_POINT=$transition_point"
        "ENTROPY_THRESHOLD=$ENTROPY_THRESHOLD"
        "BATCH_SIZE=$BATCH_SIZE"
    )
    if [[ "$task" == "kmmlu" ]]; then
        envs+=("LNG=$lang")
    fi

    local job_name="${task}_${tag}"
    local env_str
    env_str=$(IFS=,; echo "${envs[*]}")

    local cmd="sbatch --job-name=$job_name --export=ALL,$env_str $slurm_script"
    echo "[$tag/$task] $cmd"

    if [[ $SUBMIT -eq 1 ]]; then
        local jobid
        jobid=$(sbatch --job-name="$job_name" --export=ALL,"$env_str" "$slurm_script" | awk '{print $NF}')
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$(date -Iseconds)" "$jobid" "$tag" "$task" "$exp_type" \
            "$merges" "$boundary" "$transition_point" "$ENTROPY_THRESHOLD" \
            >> "$MANIFEST"
    fi
}

# --- write manifest header on first submission ------------------------------
if [[ $SUBMIT -eq 1 && ! -s "$MANIFEST" ]]; then
    printf 'submitted_at\tjob_id\tmethod\ttask\texp_type\tmerges\tboundary\ttransition_point\tentropy_threshold\n' \
        > "$MANIFEST"
fi

# --- the 16-cell loop -------------------------------------------------------
for task in mmlu kmmlu; do
    if [[ "$task" == "mmlu" ]]; then lang="en"; else lang="ko"; fi

    # Read both operating points up-front so a missing JSON aborts before submitting.
    m30_pre=$(read_m30 "$task" "$lang" "pretokens")
    m30_sup=$(read_m30 "$task" "$lang" "superbpe")
    m30_sup_half=$(( m30_sup / 2 ))

    echo "=== $task / $lang ==="
    echo "  M30(pretokens) = $m30_pre"
    echo "  M30(superbpe)  = $m30_sup  (warm-up half = $m30_sup_half)"

    #            TAG  TASK   EXP_TYPE                    MERGES        BOUNDARY    TP
    submit_cell B1   $task plain                        0             pretokens   0
    submit_cell B2   $task original_tk_hypernet         0             pretokens   0
    submit_cell M1   $task dynamic_bpe                  "$m30_pre"    pretokens   0
    submit_cell U1   $task dynamic_bpe                  "$m30_sup"    superbpe    0
    submit_cell U2   $task dynamic_bpe                  "$m30_sup"    superbpe    "$m30_sup_half"
    submit_cell S1   $task entropy_split                0             pretokens   0
    submit_cell SM1  $task dynamic_bpe_entropy_split    "$m30_pre"    pretokens   0
    submit_cell SM2  $task dynamic_bpe_entropy_split    "$m30_sup"    superbpe    0
done

if [[ $SUBMIT -eq 0 ]]; then
    echo ""
    echo "Preview only — no jobs submitted. Re-run with --submit to actually queue."
    echo "Manifest target: $MANIFEST"
else
    echo ""
    echo "Submitted. See manifest at: $MANIFEST"
fi
